name: Build Debian Package

on:
  push:
    branches: [main]
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: debian:bookworm

    steps:
      - name: Install build dependencies
        run: |
          apt-get update
          apt-get install -y build-essential pkg-config debhelper \
            libxfce4panel-2.0-dev libxfce4ui-2-dev libgtk-3-dev \
            libjson-glib-dev libsoup-3.0-dev git

      - name: Checkout
        run: |
          # Use host.docker.internal or the actual host IP for container access
          REPO_URL="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}.git"
          # Replace localhost with host.docker.internal for Docker container access
          REPO_URL=$(echo "$REPO_URL" | sed 's/localhost/host.docker.internal/g')
          git clone --depth=1 "$REPO_URL" .
          git checkout $GITHUB_SHA

      - name: Build package
        run: dpkg-buildpackage -us -uc -b

      - name: List built packages
        run: ls -la ../*.deb
