name: Build Debian Package

on:
  push:
    branches: [main]
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: debian:bookworm

    steps:
      - name: Install build dependencies
        run: |
          apt-get update
          apt-get install -y build-essential pkg-config debhelper \
            libxfce4panel-2.0-dev libxfce4ui-2-dev libgtk-3-dev \
            libjson-glib-dev libsoup-3.0-dev git

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build package
        run: dpkg-buildpackage -us -uc -b

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: debian-package
          path: ../*.deb
